name: Notion Weekly Updater

on:
  schedule:
    - cron: '0 18 * * *'  # 매일 오전 3시 (KST 기준)
  workflow_dispatch:

jobs:
  update-notion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

   #   - name: Dry run test
   #     env:
   #       DRY_RUN: true

      - name: Run Notion updater
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
        run: |
          python notion_weekly_count_updater_v2_safe.py