name: Notion Weekly Updater          # 1
on:                                  # 2
  workflow_dispatch:                 # 3

jobs:                                # 4
  update-notion:                     # 5
    runs-on: ubuntu-latest           # 6

    steps:                           # 7
      - name: Checkout repo          # 8
        uses: actions/checkout@v3    # 9

      - name: Set up Python          # 10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies   # 11
        run: pip install requests

   #   - name: Dry run test           # 12
   #     env:                         # 13
   #       DRY_RUN: true
      - name: Run Notion updater     # 14
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
        run: |
          python notion_weekly_count_updater_v2_safe.py